### ISSUE TITLE
Blender 4.0.1 can not install, error code

### ISSUE THREAD

**Issue by olemariussvendsen** [rgsouthall/vi-suite07#11]
Evening Ryan, i hope all is well. I wanted to test on my laptop the new annual glare tool i saw on github you added. I therefore installed Blender 4.0.1. Unfortionaly when trying to install VI-Suite following error code comes up:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\__init__.py", line 290, in <module>
    from .vi_display import VIEW3D_OT_WRDisplay, VIEW3D_OT_SVFDisplay, VIEW3D_OT_Li_BD, VIEW3D_OT_Li_DBSDF, VIEW3D_OT_SSDisplay, NODE_OT_SunPath, NODE_OT_Vi_Info
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\vi_display.py", line 42, in <module>
    from PyQt6.QtGui import QImage, QPdfWriter, QPagedPaintDevice, QPainter, QPageSize
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

**Comment by rgsouthall** [comment]
Hi Ole.
Thanks for the bug report. PyQt 6.6 seems to be the problem. I have committed a potential fix to master. You will need to clear out the C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\Python\win32 folder or just delete the addon folder and reinstall from master.

**Comment by olemariussvendsen** [comment]
Morning, i deleted the entire appdata folder, and tried to install the new master. Still it seems for me i get the same kinda issue. here is the errorcode this time, looks the same?



Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\__init__.py", line 294, in <module>
    from .vi_display import VIEW3D_OT_WRDisplay, VIEW3D_OT_SVFDisplay, VIEW3D_OT_Li_BD, VIEW3D_OT_Li_DBSDF, VIEW3D_OT_SSDisplay, NODE_OT_SunPath, NODE_OT_Vi_Info
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\vi_display.py", line 42, in <module>
    from PyQt6.QtGui import QImage, QPdfWriter, QPagedPaintDevice, QPainter, QPageSize
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

**Comment by olemariussvendsen** [comment]
Glad to report, i restarted my machine. THis allowed me to install VI-Suite again.

**Comment by rgsouthall** [comment]
Turned out it was a problem with PyQt6 generally, so I moved over to PySide6 yesterday and that seems to work OK.
