### ISSUE TITLE
VI-Suite v0.7 installs but can't enable addon in bopth Bledner 3.6 & 4.1

### ISSUE THREAD

**Issue by tankshield** [rgsouthall/vi-suite07#19]
Error reported in 3.6

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\vi-suite07-vi-suite07_beta2\__init__.py", line 268, in <module>
    from .vi_display import VIEW3D_OT_WRDisplay, VIEW3D_OT_SVFDisplay, VIEW3D_OT_Li_BD, VIEW3D_OT_Li_DBSDF, VIEW3D_OT_SSDisplay, NODE_OT_SunPath, NODE_OT_Vi_Info
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\vi-suite07-vi-suite07_beta2\vi_display.py", line 42, in <module>
    from PyQt6.QtGui import QImage, QPdfWriter, QPagedPaintDevice, QPainter, QPageSize
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

Error reported in 4.1

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\vi-suite07-vi-suite07_beta5\__init__.py", line 278, in <module>
    from .vi_display import VIEW3D_OT_WRDisplay, VIEW3D_OT_SVFDisplay, VIEW3D_OT_Li_BD, VIEW3D_OT_Li_DBSDF, VIEW3D_OT_SSDisplay, NODE_OT_SunPath, NODE_OT_Vi_Info
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\vi-suite07-vi-suite07_beta5\vi_display.py", line 42, in <module>
    from PySide6.QtGui import QImage, QPdfWriter, QPagedPaintDevice, QPainter, QPageSize
ModuleNotFoundError: No module named 'PySide6'

**Comment by rgsouthall** [comment]
Something weird has happened when you installed as you should have a folder in your addons directory called  vi-suite07-vi-suite07_beta5,  and in that folder an __init__.py file. You have an vi-suite07-vi-suite07_beta5_init.py file in your addons folder instead.

**Comment by tankshield** [comment]
I did try uninstalling and installing it multiple times but same errors are occurring with both beta 5 and beta 2 on respective blender versions. However bleeding edge version installed fine on blender 4.1.  I am assuming this is something to do with user-end and not packages. So closing this. Thanks.
